### ISSUE TITLE
Is this maintained anymore?

### ISSUE THREAD

**Issue by Maistho** [jBenes/angular-imgcache.js#19]
This seems like it's not being maintained anymore, the latest commit was in October (and it actually broke the api).
Would it be possible for me to take over maintenance?
ping @jBenes @SidFerreira

I would be happy to take over the repository, and will at least try to keep [my fork](https://github.com/maistho/angular-imgcache.js) updated for now.

For all the current Pull Requests:
- @icer2000 (#17): I merged your PR already, nice work!
- @fvicente (#16): I just reverted the original change (af51b2ce02df2e98e3aad88535ae0815969bd4e2), which seems to work just fine.
- @simpixelated (#14): I merged your PR, I guess I should create a npm repository as well?
- @septembermd (#13): I think angular probably should be a dependency, since it's used within the project.
- @rbose85 (#8): Using a default image while waiting for the remote is quite nice, but I think it might be better to have an option for it than for it to be default.

**Comment by andre-huehn** [comment]
I would be happy if you could take over.

Do you think there is a better way to find out if image url is a local
image, so that we do not even try to cache it?

Andre

**Comment by Maistho** [comment]
I'm not sure, but for my use case it is better to just handle the failure. Sometimes it will fail to get the image because of XHR restrictions or some other thing, and then it is better to just fallback imo. Maybe one can do both?

**Comment by jBenes** [comment]
@Maistho Hi, thanks.
Sorry, I don't really have time to maintain it. I will check repository settings during the weekend and try to share it with you.

**Comment by sidferreira** [comment]
@Maistho Go for it :)
I've been using a different approach on my projects now, but I'll share it cause maybe it helps improving it.

**Comment by Maistho** [comment]
@jBenes How's it going? 
Are you intending to transfer the repository (https://help.github.com/articles/transferring-a-repository/#to-transfer-a-repository-to-another-user-account)
Or do you just want to give me push access (https://help.github.com/articles/adding-collaborators-to-a-personal-repository/)

**Comment by Maistho** [comment]
ping @jBenes 
Not intending to bug you more than I need to (I know how it is to be busy), but granting push access or transferring the repository are both "less than 5 minutes" kind of actions. :smiley:

**Comment by gslender** [comment]
I had all sorts of problems and until I changed over to the maintained version by @Maistho it wasn't working. @jBenes if you aren't going to maintain it, please hand it over or tell @chrisben you aren't maintaining a working angular solution.

**Comment by Maistho** [comment]
Hi,

I've updated imgcache.js to point to my fork 
https://github.com/chrisben/imgcache.js/pull/163

And also updated the bower registry.
https://github.com/bower/registry/issues/184

Just installing it with bower should now give you the updated version! :tada: 

If you have any problems, please open an issue at
https://github.com/maistho/angular-imgcache.js/issues
